# Generated by Django 3.0.3 on 2020-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkport',
            options={'ordering': ('label__order',)},
        ),
    ]
