# Generated by Django 3.0.3 on 2020-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('hostname', 'asset_number')},
        ),
        migrations.AlterModelOptions(
            name='itmodel',
            options={'ordering': ['vendor', 'model_number'], 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ('rack',)},
        ),
    ]
