# Generated by Django 3.0.3 on 2020-04-08 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0009_auto_20200402_0223'),
        ('equipment', '0002_auto_20200401_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('offline', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='datacenter',
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='display_color',
            field=models.CharField(blank=True, default='#ddd', max_length=10, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', message='Please enter a valid color code.')]),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of GB of memory must be at least 0.')], verbose_name='Memory (GB)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='equipment.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='equipment.Site'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('rack', 'site', 'version')},
        ),
        migrations.RemoveField(
            model_name='rack',
            name='datacenter',
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
    ]
