# Generated by Django 3.0.3 on 2020-04-08 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200408_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack_position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')]),
        ),
    ]
