# Generated by Django 3.0.3 on 2020-04-14 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200408_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='blade_chassis',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blade', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='slot',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1, message='Chassis slot position must be at least 1.'), django.core.validators.MaxValueValidator(14, message='Chassis slot position must be at most 14.')]),
        ),
        migrations.AddField(
            model_name='itmodel',
            name='type',
            field=models.CharField(choices=[('regular', 'regular'), ('chassis', 'chassis'), ('blade', 'blade')], default='regular', max_length=16),
            preserve_default=False,
        ),
    ]
