# Generated by Django 3.0.3 on 2020-04-17 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20200414_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='blade_chassis',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blade_set', to='equipment.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack_position',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')]),
        ),
    ]
