# Generated by Django 3.0.2 on 2020-04-17 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20200417_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='display_color',
            field=models.CharField(blank=True, default='#ddd', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', message='Please enter a valid color code.')]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
