# Generated by Django 3.0.4 on 2020-03-30 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_perm', models.BooleanField(default=False, verbose_name='Model Management')),
                ('asset_perm', models.BooleanField(default=False, verbose_name='Asset Management')),
                ('power_perm', models.BooleanField(default=False, verbose_name='Power Permission')),
                ('audit_perm', models.BooleanField(default=False, verbose_name='Audit Permission')),
                ('admin_perm', models.BooleanField(default=False, verbose_name='Admin Permission')),
                ('datacenter_perm', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('GLOBAL', 'Global')], max_length=6, verbose_name='Datacenter Permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
