# Generated by Django 3.0.2 on 2020-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='datacenter_perm',
            field=models.CharField(blank=True, max_length=10000, verbose_name="Site Permission (Enter existing site abbreviations comma-separated. For global, enter 'Global')"),
        ),
    ]
