# Generated by Django 3.0.2 on 2020-04-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyposoft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perms',
        ),
    ]
