# Generated by Django 3.0.4 on 2020-03-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changeplan', '0001_initial'),
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powereddiff',
            name='changed_powered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_powered', to='power.Powered'),
        ),
        migrations.AddField(
            model_name='powereddiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AddField(
            model_name='powereddiff',
            name='live_powered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_powered', to='power.Powered'),
        ),
        migrations.AddField(
            model_name='networkportdiff',
            name='changed_networkport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_networkport', to='network.NetworkPort'),
        ),
        migrations.AddField(
            model_name='networkportdiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AddField(
            model_name='networkportdiff',
            name='live_networkport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_networkport', to='network.NetworkPort'),
        ),
        migrations.AddField(
            model_name='changeplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AddField(
            model_name='assetdiff',
            name='changed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_asset', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='assetdiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AddField(
            model_name='assetdiff',
            name='live_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_asset', to='equipment.Asset'),
        ),
        migrations.AlterUniqueTogether(
            name='changeplan',
            unique_together={('owner', 'name')},
        ),
    ]
