# Generated by Django 3.0.3 on 2020-04-01 23:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0002_auto_20200330_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdiff',
            name='conflicts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
