# Generated by Django 3.0.3 on 2020-04-02 00:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0003_assetdiff_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkportdiff',
            name='conflicts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powereddiff',
            name='conflicts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
