# Generated by Django 3.0.3 on 2020-04-02 02:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0007_auto_20200402_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdiff',
            old_name='message',
            new_name='messages',
        ),
        migrations.RemoveField(
            model_name='networkportdiff',
            name='message',
        ),
        migrations.RemoveField(
            model_name='powereddiff',
            name='message',
        ),
        migrations.AddField(
            model_name='networkportdiff',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powereddiff',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=[], size=None),
            preserve_default=False,
        ),
    ]
