# Generated by Django 3.0.3 on 2020-04-02 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0008_auto_20200402_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdiff',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='networkportdiff',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='powereddiff',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None),
        ),
    ]
