# Generated by Django 3.0.3 on 2020-04-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_auto_20200419_0846'),
        ('changeplan', '0009_auto_20200402_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powereddiff',
            name='changed_powered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_powered', to='power.Powered'),
        ),
    ]
