# Generated by Django 3.0.3 on 2020-04-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200401_1200'),
        ('changeplan', '0010_auto_20200419_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkportdiff',
            name='changed_networkport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_networkport', to='network.NetworkPort'),
        ),
    ]
