# Generated by Django 3.0.3 on 2020-04-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powered',
            options={'ordering': ('asset__asset_number', 'asset_id', 'order')},
        ),
    ]
