# Generated by Django 3.0.4 on 2020-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Destroy', 'Destroy'), ('Decommission', 'Decommission')], max_length=16)),
                ('username', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=185)),
                ('model', models.CharField(max_length=128)),
                ('instance_id', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=128)),
                ('field_changed', models.CharField(blank=True, max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=8192)),
                ('new_value', models.CharField(blank=True, max_length=8192)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
